---
name: Build Documentation

on:
  workflow_call:
    inputs:
      salt-version:
        type: string
        required: true
        description: The Salt version to set prior to building packages.
      cache-seed:
        required: true
        type: string
        description: Seed used to invalidate caches

jobs:
  build:
    name: Build
    runs-on:
      - self-hosted
      - linux
      - medium
      - x86_64
    strategy:
      fail-fast: false
      matrix:
        docs-output:
          - linkcheck
          - spellcheck
          - html
          - epub
          # - pdf

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604 # v2.5.0
        with:
          egress-policy: audit

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Download Release Patch
        if: ${{ startsWith(github.event.ref, 'refs/tags') == false }}
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: salt-${{ inputs.salt-version }}.patch

      - name: Get Python Version
        id: get-python-version
        uses: ./.github/actions/get-python-version
        with:
          python-binary: python3

      - name: Setup Python Tools Scripts
        id: python-tools-scripts
        uses: ./.github/actions/setup-python-tools-scripts

      - name: Configure Git
        if: ${{ startsWith(github.event.ref, 'refs/tags') == false }}
        run: |
          tools pkg configure-git

      - name: Apply release patch
        if: ${{ startsWith(github.event.ref, 'refs/tags') == false }}
        run: |
          tools pkg apply-release-patch salt-${{ inputs.salt-version }}.patch --delete

      - name: Cache Python Tools Docs Virtualenv
        id: tools-venvs-dependencies-cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: .tools-venvs/docs
          key: ${{ inputs.cache-seed }}|${{ github.workflow }}|${{ github.job }}|tools-venvs|${{ steps.python-tools-scripts.outputs.version }}|docs|${{ steps.get-python-version.outputs.version }}|${{ hashFiles('requirements/**/docs.txt') }}

      - name: Prepare Docs Build
        run: |
          git clone https://gitlab.com/saltstack/open/docs/builddocs.git .builddocs
          sudo mkdir -p /usr/share/fonts/truetype /usr/share/fonts/opentype
          sudo cp -rfv .builddocs/builddocs/files/fonts/truetype/*.ttf /usr/share/fonts/truetype/
          sudo cp -rfv .builddocs/builddocs/files/fonts/opentype/*.otf /usr/share/fonts/opentype/
          sudo fc-cache -f -v

      - name: Build Documentation (${{ matrix.docs-output }})
        id: build-docs
        shell: bash
        continue-on-error: ${{ matrix.docs-output == 'linkcheck' || matrix.docs-output == 'spellcheck' }}
        env:
          LATEST_RELEASE: "${{ inputs.salt-version }}"
          SALT_ON_SALTSTACK: "1"
          ARCHIVE_FILENAME: "${{ format('salt-{0}-docs-{1}.tar.xz', inputs.salt-version, matrix.docs-output) }}"
        run: |
          tools docs ${{ matrix.docs-output }}

      - name: Upload Built Documentation Artifact(${{ matrix.docs-output }})
        if: ${{ steps.build-docs.outputs.has-artifacts == 'true' }}
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: ${{ steps.build-docs.outputs.artifact-name }}
          path: ${{ steps.build-docs.outputs.artifact-path }}
          retention-days: 7
          if-no-files-found: error
