---
name: Upload VirusTotal

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      salt-version:
        type: string
        required: true
        description: >
          The Salt version to get from staging to upload to VirusTotal.
          (DO NOT prefix the version with a v, ie, 3006.0 NOT v3006.0).

permissions:
  contents: read

jobs:
  upload-virustotal:
    name: Upload VirusTotal
    environment: release
    runs-on:
      - self-hosted
      - linux
      - repo-release
    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604 # v2.5.0
      with:
        egress-policy: audit

    - name: Checkout Salt
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Set Up Python 3.10
      uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
      with:
        python-version: "3.10"

    - name: Setup Python Tools Scripts
      uses: ./.github/actions/setup-python-tools-scripts

    - name: Upload to VirusTotal
      env:
        VIRUSTOTAL_API_KEY: ${{ secrets.VIRUSTOTAL_API_KEY }}
      run: |
        tools release upload-virustotal ${{ inputs.salt-version || github.ref_name }}
