---
name: New Issues Triage Assignment
concurrency: 1
on:
  issues:
    types: [opened]


env:
  PIP_INDEX_URL: https://pypi-proxy.saltstack.net/root/local/+simple/
  PIP_EXTRA_INDEX_URL: https://pypi.org/simple


permissions:
  contents: read

jobs:
  label-and-assign:
    permissions:
      actions: read  # for dawidd6/action-download-artifact to query and download artifacts
      contents: read  # for actions/checkout to fetch code
      issues: write
      pull-requests: read  # for dawidd6/action-download-artifact to query commit hash
    name: Triage New Issue
    runs-on: ubuntu-latest
    steps:

      - name: Harden Runner
        uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604 # v2.5.0
        with:
          egress-policy: audit

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Set up Python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install pygithub

      - name: Download last assignment cache
        continue-on-error: true
        uses: dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615 # v2.27.0
        with:
          workflow: triage.yml
          name: last-assignment
          path: .cache

      - name: Label And Assign
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          READ_ORG_TOKEN: ${{ secrets.READ_ORG_TEAM_MEMBERS_ISSUE_TRIAGE }}
        run: |
          python .github/workflows/scripts/label-and-assign.py \
            --org ${{ github.repository_owner }} \
            --repo ${{ github.event.repository.name }} \
            --team team-triage \
            --label needs-triage \
            --issue ${{ github.event.issue.number }}

      - name: Upload last assignment cache
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: last-assignment
          path: .cache
